[package]
name = "nrjmeter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#rust_gpiozero = "^0.2"
#config = "0.13"
gpio-cdev = "0.5.1"
async-nats = "0.21.0"
tokio = "1.21.2"
chrono = "0.4.22"
#sprintf = "0.1.3"