[package]
name = "nrjmeter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#rust_gpiozero = "^0.2"
#config = "0.13"
gpio-cdev = "0.5.1"
nats = "0.20.1"
sprintf = "0.1.2"