[package]
name = "nrjmeter"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio-cdev = "0.5.1"
async-nats = "0.25.0"
tokio = "1.23.0"
chrono = "0.4.23"
serde_json = "1.0.91"
serde = "1.0.151"